[project]
name = "Classihacking"
version = "0.1.0"
description = "Add a short description here"
authors = ["Rahul Dave <rahuldave@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = ">=3.12.3,<3.13"
pandas = ">=2.2.2,<2.3"
jupyter = ">=1.0.0,<1.1"
matplotlib = ">=3.8.4,<3.9"
numpy = ">=1.26.4,<1.27"
scikit-learn = ">=1.4.2,<1.5"
seaborn = ">=0.13.2,<0.14"
